apiVersion: v1
kind: Service
metadata:
  name: sidecar-poc-service
  labels:
    name: sidecar-poc-service
spec:
  ports:
    - nodePort: 30163 
      port: 8080      
      targetPort: 8080  
      protocol: TCP
  selector:           
    app: springboot-k8s
  type: NodePort       

